#!/bin/bash
#SBATCH --image=audreykoz/gradient:latest --volume="{}:/gradient_boosted/exports"
#SBATCH --qos=regular
#SBATCH --time={}
#SBATCH  -N {} -c {}
#SBATCH --constraint={}
#SBATCH --licenses=cfs,SCRATCH

cd {}

export THREADS=32

runcommands.sh {}
