#!/bin/bash
#SBATCH -A m2218
#SBATCH --image=eramey16/monocle:latest --volume="{}:/gradient_boosted/exports"
#SBATCH --qos=regular
#SBATCH --time={}
#SBATCH -N {} -c {}
#SBATCH --licenses=cfs,SCRATCH
#SBATCH --constraint={}

cd {}

export THREADS=32

runcommands.sh {}
